spring.application.name=01-blog

server.port=8080

# SSL Certificat settings
# server.ssl.enabled=true
# server.ssl.key-store=certs/blog.p12
# server.ssl.key-store-password=${CERT_PASSWORD}
# server.ssl.key-store-type=PKCS12
# server.ssl.key-alias=${CERT_ALIAS}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


# Storage settings
app.upload.dir=uploads
app.max.file.size=10MB

# Database settings
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Flyway settings
spring.flyway.enabled=true
spring.flyway.locations=filesystem:/app
spring.flyway.out-of-order=true
# logging.level.org.springframework.security=INFO
# logging.level.org.springframework.web=INFO
# logging.level.io.jsonwebtoken=ERROR

# server.error.include-stacktrace=never
# server.error.include-message=never



jwt.secret=${JWT_SECRET}

logging.level.org.springframework.security=DEBUG

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false
management.endpoints.web.exposure.include=mappings

